TheCSharpAcademy/TCSA.V2

- TCSA.V2/Components/Pages/ProjectPage.razor
- TCSA.V2/Components/TopMenu.razor
- TCSA.V2/Helpers/Enums.cs
- TCSA.V2/Helpers/ProjectHelper.cs
- TCSA.V2/Helpers/ProjectsSubHelpers/StandAloneProjectsHelper.cs
Add the translation for freecodecamp to Dutch
> #19 translate freecodecamp project to Dutch

- TCSA.V2/Helpers/ProjectHelper.cs
- TCSA.V2/Helpers/ProjectsSubHelpers/ConsoleProjectsHelper.cs
Adds translation for Math Game into Dutch.
I also include the rest of the projects there in English within a comment, to make it easier to pick one up and translate it by others
> Add Dutch translation for Math Game

- TCSA.V2/Helpers/Enums.cs
- TCSA.V2/Helpers/ProjectHelper.cs
- TCSA.V2/Helpers/ProjectsSubHelpers/StandAloneProjectsHelper.cs
First time working on a project like this
Please let me know if there's any issues.
> Korean translation completed on standAlone

- TCSA.V2/Helpers/ProjectsSubHelpers/ConsoleProjectsHelper.cs
added translation for console math game project
still not too confident about merging. please let me know if there's nay issue.
> added translation for console math game project

- TCSA.V2/Components/Dashboard/Pages/Dashboard.razor
The cloud area was listing the Auth projects. It's fixed now.
> Fixed Cloud area showing Auth projects.

- TCSA.V2/Helpers/ProjectsSubHelpers/ConsoleProjectsHelper.cs
As you can see in the issue #206, the Sports Results Notifier project contains a tip that’s irrelevant. 
In this PR I removed the tip. The project wasn’t translated yet, but it is in progress to be translated to Dutch and Korean, so I removed the tip also from those commented out parts.
Please let me know if you want to show a different tip instead of removing it. Happy to change it.
> Remove irrelevant tip from project

- TCSA.V2/Helpers/ProjectsSubHelpers/ConsoleProjectsHelper.cs
translated the coding tracker project to dutch
> 208 translate coding tracker to dutch

- TCSA.V2/Components/Pages/ProjectPage.razor
- TCSA.V2/Helpers/Enums.cs
- TCSA.V2/Helpers/ProjectsSubHelpers/ConsoleProjectsHelper.cs
This refactor makes a number of Project properties be gathered from the main english translation instead of re-entering them, making the ability to update projects in the future less error-prone.
> Refactor project translations

- TCSA.V2/Components/Main/MainBanner.razor
- TCSA.V2/Components/Pages/Home.razor
- TCSA.V2/Components/Pages/IndexProjectSection.razor
- TCSA.V2/wwwroot/app.css
This PR will:
1.  Align lead colors with original light theme
2. Update auth section title
3. Make sure description of start applying section is visible (currently not visible on PRODUCTION website)
> Fix dark mode review comments

- TCSA.V2/Components/Admin/Pages/UserDetail.razor
> 245 fix ranking in email

- TCSA.V2/Helpers/ProjectsSubHelpers/MVCProjectsHelper.cs
Previously the description said that the project would follow a tutorial in the official documentation. This isn't strictly true, since there isn't any one tutorial that features MVC, a minimal API, and Javascript/Fetch API. There was some confusion on my part and I think for a couple others as well, since some of the projects in the repo do not include all those elements either. 
I have changed the description, requirements, and resources to better reflect the need to incorporate all three elements into the project. Users will now be pointed to two different tutorials in the docs as well as the previously included video.
> 221 fix todo list project instructions

- TCSA.V2/Components/Dashboard/Pages/Dashboard.razor
- TCSA.V2/Components/UI/BeltNotificationModal.razor
I got a basic modal up and running. It's very simple but visually cohesive with the site. I am using the same belt images as other locations on the site
The modal works just by checking the HasPendingBeltUpdate bool and then displaying if true, then reseting the bool to false on close. It reads the correct belt to use based on the user's level property.
One small issue is that I couldn't get the bootstrap fade class to work properly. It did work once or twice and then stopped, but I couldn't reproduce what I changed. Let me know if it fades in and out correctly for you.
> 298 create good looking modal for belt update

- TCSA.V2/Components/Layout/MainLayout.razor
- TCSA.V2/Program.cs
- TCSA.V2/Services/HeartBeat.cs
Currently ping interval set to 5 minutes. It is just returning a string so there should not be a performance issue.
> Sending a ping to server side to keep connection alive

- TCSA.V2/Components/Dashboard/Pages/Community.razor
changed elements alignment to center
> Update project submit form elements

- TCSA.V2/Components/Dashboard/DashboardIssueCard.razor
- TCSA.V2/Components/UI/SVGs/PendingReviewSVG.razor
Helllo @TheCSharpAcademy I've tried to be coherent with the other icons:
> Fix pending review icon

- TCSA.V2/Components/Dashboard/DashboardReviewCard.razor
- TCSA.V2/Components/Dashboard/Pages/PeerReviews.razor
- TCSA.V2/Helpers/DateTimeHelper.cs
> Adds duration since submitted to peer review card

- TCSA.V2/Helpers/ProjectsSubHelpers/ConsoleProjectsHelper.cs
fix typo
- from stackoveflow.com to stackoverflow.com
> fix typo in ConsoleProjectsHelper.cs

- TCSA.V2/Components/App.razor
- TCSA.V2/Components/Dashboard/Pages/Activity.razor
- TCSA.V2/Components/Dashboard/Pages/Challenges.razor
- TCSA.V2/Components/Dashboard/Pages/Community.razor
- TCSA.V2/Components/Dashboard/Pages/Dashboard.razor
- TCSA.V2/Components/Dashboard/Pages/Leaderboard.razor
- TCSA.V2/Components/Dashboard/Pages/PeerReviews.razor
- TCSA.V2/Components/Dashboard/Pages/Profile.razor
- TCSA.V2/Components/Dashboard/Pages/ProjectSubmission.razor
- TCSA.V2/Components/Dashboard/Pages/Roadmap.razor
- TCSA.V2/Components/Pages/ArticlePage.razor
- TCSA.V2/Components/Pages/Home.razor
- TCSA.V2/Components/Pages/ProjectPage.razor
- TCSA.V2/Components/Pages/PublicLeaderboard.razor
- TCSA.V2/Helpers/StringConstants.cs
adds titles to all pages - either default as "The C# Academy" or appended with project, article or page name
> Add titles to all pages

- TCSA.V2/Components/Dashboard/Pages/Dashboard.razor
- TCSA.V2/Components/Pages/ProjectPage.razor
- TCSA.V2/Services/PeerReviewService.cs
- TCSA.V2/Services/ProjectService.cs
> Added Number of Users who have completed a project

- TCSA.V2/Components/Dashboard/Pages/Dashboard.razor
- TCSA.V2/Components/Pages/Home.razor
- TCSA.V2/Helpers/ProjectsSubHelpers/StandAloneProjectsHelper.cs
- TCSA.V2/Models/Article.cs
Separated Flagship and Freestyle projects to different Areas, because keeping them in Graduation Projects caused not detecting area as completed in dashboard
> Dashboard Flagship Area fix

- TCSA.V2/Helpers/CourseHelper.cs
Fixes #443 
This PR uses human-friendly names to display book names.
> Use human friendly display for `Delete Book` functionality in OOP Crash Course
